### ISSUE TITLE
cwdPackage is not defined

### ISSUE THREAD

**Issue by eldisgustin** [cahnory/deadcode#1]
I tried to use the package but I'm getting this error out of the box:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/8430727/56367574-85a1c800-61c3-11e9-9179-cfc6266755a8.png">

My Node version:`v11.13.0`

Tried installing it as a global dependency and as a local dependency of my project, same result.

**Comment by cahnory** [comment]
Sorry @agonzalezmurua, I missed the notification. I just publish a fix (#2) for this (first 😉) issue.
Thank you for your help !
